// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-YsgLmEVxHTRZ258bAEylMJgCeiOe_X4',
    appId: '1:52080048504:web:bb283e23b16323abbf708d',
    messagingSenderId: '52080048504',
    projectId: 'foodgo-1eabe',
    authDomain: 'foodgo-1eabe.firebaseapp.com',
    storageBucket: 'foodgo-1eabe.firebasestorage.app',
    measurementId: 'G-WPD4QHT2R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW8Qk_RE6V5JL5JFthY48QoFfCffCJwjY',
    appId: '1:52080048504:android:1e7463d18197bb2bbf708d',
    messagingSenderId: '52080048504',
    projectId: 'foodgo-1eabe',
    storageBucket: 'foodgo-1eabe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSukwpjus5utmZowtHZzaUREd9XxWCSrs',
    appId: '1:52080048504:ios:4c22912552c5ede2bf708d',
    messagingSenderId: '52080048504',
    projectId: 'foodgo-1eabe',
    storageBucket: 'foodgo-1eabe.firebasestorage.app',
    iosBundleId: 'com.example.fooddeliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSukwpjus5utmZowtHZzaUREd9XxWCSrs',
    appId: '1:52080048504:ios:4c22912552c5ede2bf708d',
    messagingSenderId: '52080048504',
    projectId: 'foodgo-1eabe',
    storageBucket: 'foodgo-1eabe.firebasestorage.app',
    iosBundleId: 'com.example.fooddeliveryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-YsgLmEVxHTRZ258bAEylMJgCeiOe_X4',
    appId: '1:52080048504:web:c86cea0b486246e4bf708d',
    messagingSenderId: '52080048504',
    projectId: 'foodgo-1eabe',
    authDomain: 'foodgo-1eabe.firebaseapp.com',
    storageBucket: 'foodgo-1eabe.firebasestorage.app',
    measurementId: 'G-Q2Y6QN7QW2',
  );
}
